import pandera as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
    'Investment No.': Column(pa.String, nullable=False, coerce=True),
    'Status': Column(pa.String, nullable=False, coerce=True),
    'Project Name (Eng)': Column(pa.String, nullable=False, coerce=True),
    'Project Name (Jpn)': Column(pa.String, nullable=False, coerce=True),
    'Capitalized/Non-capitalized': Column(pa.String, nullable=False, coerce=True),
    'Cost Global （M JPY）': Column(pa.Float, nullable=False, coerce=True),
    'FY2016': Column(pa.Float, nullable=True, coerce=True),
    'FY2017': Column(pa.Float, nullable=True, coerce=True),
    'FY2018': Column(pa.Float, nullable=True, coerce=True),
    'FY2019': Column(pa.Float, nullable=True, coerce=True),
    'FY2020': Column(pa.Float, nullable=True, coerce=True),
    'FY2021': Column(pa.Float, nullable=True, coerce=True),
    'FY2022': Column(pa.Float, nullable=True, coerce=True),
    'FY2023': Column(pa.Float, nullable=True, coerce=True),
    'FY2024': Column(pa.Float, nullable=True, coerce=True),
    'FY2025': Column(pa.Float, nullable=True, coerce=True),
    'FY2026': Column(pa.Float, nullable=True, coerce=True),
    'FY2027': Column(pa.Float, nullable=True, coerce=True),
    'FY2028': Column(pa.Float, nullable=True, coerce=True),
    'FY2029': Column(pa.Float, nullable=True, coerce=True),
    'FY2030': Column(pa.Float, nullable=True, coerce=True),
    'FY2031': Column(pa.Float, nullable=True, coerce=True),
    'FY2032': Column(pa.Float, nullable=True, coerce=True),
    'FY2033': Column(pa.Float, nullable=True, coerce=True),
    'FY2034': Column(pa.Float, nullable=True, coerce=True),
    'FY2035': Column(pa.Float, nullable=True, coerce=True),
    'FY2036': Column(pa.Float, nullable=True, coerce=True),
    'FY2037': Column(pa.Float, nullable=True, coerce=True),
    'FY2038': Column(pa.Float, nullable=True, coerce=True),
    'FY2039': Column(pa.Float, nullable=True, coerce=True),
    'FY2040': Column(pa.Float, nullable=True, coerce=True),
    'FY2041': Column(pa.Float, nullable=True, coerce=True),
    'FY2042': Column(pa.Float, nullable=True, coerce=True),
    'FY2043': Column(pa.Float, nullable=True, coerce=True),
    'FY2044': Column(pa.Float, nullable=True, coerce=True),
    'FY2045': Column(pa.Float, nullable=True, coerce=True),
    'FY2046': Column(pa.Float, nullable=True, coerce=True),
    'FY2047': Column(pa.Float, nullable=True, coerce=True),
    'FY2048': Column(pa.Float, nullable=True, coerce=True),
    'FY2049': Column(pa.Float, nullable=True, coerce=True),
    'FY2050': Column(pa.Float, nullable=True, coerce=True),
    'FY2051': Column(pa.Float, nullable=True, coerce=True),
    'FY2052': Column(pa.Float, nullable=True, coerce=True),
    'FY2053': Column(pa.Float, nullable=True, coerce=True),
    'FY2054': Column(pa.Float, nullable=True, coerce=True),
    'FY2055': Column(pa.Float, nullable=True, coerce=True),
    'FY2056': Column(pa.Float, nullable=True, coerce=True),
    'FY2057': Column(pa.Float, nullable=True, coerce=True),
    'FY2058': Column(pa.Float, nullable=True, coerce=True),
    'FY2059': Column(pa.Float, nullable=True, coerce=True),
    'FY2060': Column(pa.Float, nullable=True, coerce=True),
    'FY2061': Column(pa.Float, nullable=True, coerce=True),
    'FY2062': Column(pa.Float, nullable=True, coerce=True),
    'FY2063': Column(pa.Float, nullable=True, coerce=True),
    'FY2064': Column(pa.Float, nullable=True, coerce=True),
    'Airport': Column(pa.String, nullable=False, coerce=True),
    'Project Major Categories (Eng)': Column(pa.String, nullable=False, coerce=True),
    'Project Major Categories (Jpn)': Column(pa.String, nullable=False, coerce=True),
    'Facility Major Categories': Column(pa.String, nullable=False, coerce=True),
    'Facility Sub Categories': Column(pa.String, nullable=False, coerce=True),
    'Facility Minor Categories': Column(pa.String, nullable=False, coerce=True),
    'Type': Column(pa.String, nullable=False, coerce=True),
    'Purpose': Column(pa.String, nullable=False, coerce=True),
    'Major Classification': Column(pa.String, nullable=False, coerce=True),
    'Super Important Project': Column(pa.String, nullable=True, coerce=True),
    'Environment': Column(pa.String, nullable=True, coerce=True),
    'Line CXO': Column(pa.String, nullable=False, coerce=True),
    'Budget Department': Column(pa.String, nullable=False, coerce=True),
    'PO': Column(pa.String, nullable=False, coerce=True),
    "PO's Company": Column(pa.String, nullable=False, coerce=True),
    "PO's Department": Column(pa.String, nullable=False, coerce=True),
    "PO's Group": Column(pa.String, nullable=False, coerce=True),
    'PM': Column(pa.String, nullable=False, coerce=True),
    "PM's Company": Column(pa.String, nullable=False, coerce=True),
    "PM's Department": Column(pa.String, nullable=False, coerce=True),
    "PM's Group": Column(pa.String, nullable=False, coerce=True),
    'Go Date': Column(pa.String, nullable=True, coerce=True),
    'Go Amount': Column(pa.Float, nullable=True, coerce=True),
    'Re-go Date': Column(pa.String, nullable=True, coerce=True),
    'Re-go Amount': Column(pa.Float, nullable=True, coerce=True),
    'Design V': Column(pa.String, nullable=True, coerce=True),
    'Selection V': Column(pa.String, nullable=True, coerce=True),
    'Contract': Column(pa.String, nullable=True, coerce=True),
    'Completion': Column(pa.String, nullable=True, coerce=True),
    'Completion Amount': Column(pa.Float, nullable=True, coerce=True),
    'Delivery': Column(pa.String, nullable=True, coerce=True),
    'Asset Holder': Column(pa.String, nullable=True, coerce=True),
    'Option': Column(pa.String, nullable=True, coerce=True),
    'Expansion approve': Column(pa.String, nullable=True, coerce=True),
    'Outstanding Capital Expense': Column(pa.Float, nullable=True, coerce=True),
    'Entrusted Type': Column(pa.String, nullable=True, coerce=True),
    'Account Title': Column(pa.String, nullable=True, coerce=True),
    'Useful Life By Law': Column(pa.String, nullable=True, coerce=True),
    'HMP': Column(pa.String, nullable=True, coerce=True),
    'ARO': Column(pa.String, nullable=True, coerce=True),
    'Performance Improvement Investment (UKB)': Column(pa.String, nullable=True, coerce=True),
    'Retirement Value': Column(pa.Float, nullable=True, coerce=True),
    'Project IRR': Column(pa.Float, nullable=True, coerce=True),
    'IRR Term': Column(pa.String, nullable=True, coerce=True),
    'Memo': Column(pa.String, nullable=True, coerce=True),
},
    strict=True,
    coerce=True,
)