import pandera as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
    'ACCOUNTNO_NAME': Column(pa.String, nullable=True, coerce=True),
    'ACCOUNTEXSEG': Column(pa.String, nullable=True, coerce=True),
    'ACCOUNTNAME': Column(pa.String, nullable=True, coerce=True),
    'ACCTTYPE': Column(pa.String, nullable=True, coerce=True),
    'YEAR': Column(pa.Float, nullable=True, coerce=True),
    'PERIOD': Column(pa.Float, nullable=True, coerce=True),
    'DATE': Column(pa.DateTime, nullable=True, coerce=True),
    'SRCE CODE': Column(pa.String, nullable=True, coerce=True),
    'REFERENCE': Column(pa.String, nullable=True, coerce=True),
    'DESCRIPTION': Column(pa.String, nullable=True, coerce=True),
    'POSTINGSEQ': Column(pa.String, nullable=True, coerce=True),
    'BATCHNO': Column(pa.String, nullable=True, coerce=True),
    'ENTRYNBR': Column(pa.String, nullable=True, coerce=True),
    'AUDITDATE': Column(pa.DateTime, nullable=True, coerce=True),
    'AUDITUSER': Column(pa.String, nullable=True, coerce=True),
    'FC CODE': Column(pa.String, nullable=True, coerce=True),
    'FC AMOUNT': Column(pa.Float, nullable=True, coerce=True),
    'HC CODE': Column(pa.String, nullable=True, coerce=True),
    'DEBIT': Column(pa.Float, nullable=True, coerce=True),
    'CREDIT': Column(pa.Float, nullable=True, coerce=True),
    'ACCTDESC': Column(pa.String, nullable=True, coerce=True),
    'COMPANYNAME': Column(pa.String, nullable=True, coerce=True),
    'ACSEGVAL01': Column(pa.Float, nullable=True, coerce=True),
    'ACSEGVAL02': Column(pa.String, nullable=True, coerce=True),
    'ACSEGVAL03': Column(pa.Float, nullable=True, coerce=True),
    'ACSEGVAL04': Column(pa.Float, nullable=True, coerce=True),
    'IATA': Column(pa.String, nullable=True, coerce=True),
    'ACCTGRPCOD': Column(pa.Float, nullable=True, coerce=True),
    'ACCTGRPDES': Column(pa.String, nullable=True, coerce=True),
    'Customer': Column(pa.String, nullable=True, coerce=True),
    'CustomerId': Column(pa.String, nullable=True, coerce=True),
    'Proveedor': Column(pa.String, nullable=True, coerce=True),
    'ProveedorId': Column(pa.String, nullable=True, coerce=True),
    'DRILAPP': Column(pa.String, nullable=True, coerce=True),
    'DRILLDWNLK': Column(pa.Float, nullable=True, coerce=True),
    'DRILSRCTY': Column(pa.Float, nullable=True, coerce=True),
},
    strict=True,
    coerce=True,
)
