import pandera as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
    'ACCTID': Column(pa.String, nullable=True, coerce=True),
    'FSCSYR': Column(pa.Float, nullable=True, coerce=True),
    'FSCSDSG': Column(pa.Float, nullable=True, coerce=True),
    'FSCSCURN': Column(pa.String, nullable=True, coerce=True),
    'CURNTYPE': Column(pa.String, nullable=True, coerce=True),
    'SWRVL': Column(pa.Float, nullable=True, coerce=True),
    'CODERVL': Column(pa.Float, nullable=True, coerce=True),
    'SCURNDEC': Column(pa.Float, nullable=True, coerce=True),
    'OPENBAL': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD1': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD2': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD3': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD4': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD5': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD6': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD7': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD8': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD9': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD10': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD11': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD12': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD13': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD14': Column(pa.Float, nullable=True, coerce=True),
    'NETPERD15': Column(pa.Float, nullable=True, coerce=True),
    'DATECONV': Column(pa.Float, nullable=True, coerce=True),
    'SPECURNSW': Column(pa.Float, nullable=True, coerce=True),
    'NETCHGSW': Column(pa.Float, nullable=True, coerce=True),
    'CONVSW': Column(pa.Float, nullable=True, coerce=True),
    'TOTALAMT': Column(pa.Float, nullable=True, coerce=True),
    'PERD01BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD02BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD03BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD04BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD05BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD06BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD07BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD08BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD09BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD10BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD11BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD12BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD13BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD14BAL': Column(pa.Float, nullable=True, coerce=True),
    'PERD15BAL': Column(pa.Float, nullable=True, coerce=True),
    'REPLACESW': Column(pa.Float, nullable=True, coerce=True),
    'RATETYPE': Column(pa.Float, nullable=True, coerce=True),
    'OVRDRATE': Column(pa.Float, nullable=True, coerce=True),
    'ACTIVITYSW': Column(pa.Float, nullable=True, coerce=True),
},
    strict=True,
    coerce=True,
)
