import pandera as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
    'Data de corte': Column(pa.Float, nullable=True, coerce=True),
    'CANCELED': Column(pa.String, nullable=True, coerce=True),
    'BPLName': Column(pa.String, nullable=True, coerce=True),
    'Origem': Column(pa.String, nullable=True, coerce=True),
    'DocEntry': Column(pa.Float, nullable=True, coerce=True),
    'DocNum': Column(pa.Float, nullable=True, coerce=True),
    'CardCode': Column(pa.String, nullable=True, coerce=True),
    'CardName': Column(pa.String, nullable=True, coerce=True),
    'Natureza': Column(pa.String, nullable=True, coerce=True),
    'U_SD_TipoFat': Column(pa.String, nullable=True, coerce=True),
    'Comments': Column(pa.String, nullable=True, coerce=True),
    'Series': Column(pa.Float, nullable=True, coerce=True),
    'DocDate': Column(pa.DateTime, nullable=True, coerce=True),
    'DocDueDate': Column(pa.DateTime, nullable=True, coerce=True),
    'Chave Nota': Column(pa.String, nullable=True, coerce=True),
    'Nro Nota': Column(pa.Float, nullable=True, coerce=True),
    'NumRPS': Column(pa.Float, nullable=True, coerce=True),
    'DpmAmnt': Column(pa.Float, nullable=True, coerce=True),
    'DocTotal': Column(pa.Float, nullable=True, coerce=True),
    'TipoFaturamento': Column(pa.String, nullable=True, coerce=True),
    'PaidToDate': Column(pa.Float, nullable=True, coerce=True),
    'CR Normal': Column(pa.Float, nullable=True, coerce=True),
    'Data Baixa CR': Column(pa.DateTime, nullable=True, coerce=True),
    'ValorBaixa': Column(pa.Float, nullable=True, coerce=True),
    'ContaBaixa': Column(pa.String, nullable=True, coerce=True),
    'ValorBruto': Column(pa.Float, nullable=True, coerce=True),
    'DiasDeAtraso': Column(pa.Float, nullable=True, coerce=True),
    'Multa': Column(pa.Float, nullable=True, coerce=True),
    'Juros': Column(pa.Float, nullable=True, coerce=True),
    'TotalJurosMulta': Column(pa.Float, nullable=True, coerce=True),
    'AppliedSys': Column(pa.Float, nullable=True, coerce=True),
    'NossoNumero': Column(pa.String, nullable=True, coerce=True),
    'SituacaoCR': Column(pa.String, nullable=True, coerce=True),
    'ValorDoBoleto': Column(pa.Float, nullable=True, coerce=True),
    'Vcto do Boleto': Column(pa.DateTime, nullable=True, coerce=True),
    'DataDoPagamento': Column(pa.DateTime, nullable=True, coerce=True),
    'Data Pagto': Column(pa.DateTime, nullable=True, coerce=True),
    'DocEntry.1': Column(pa.Float, nullable=True, coerce=True),
    'EntityId': Column(pa.Float, nullable=True, coerce=True),
    'DataDeEnvio': Column(pa.DateTime, nullable=True, coerce=True),
    'Hora de Envio': Column(pa.String, nullable=True, coerce=True),
    'Situação': Column(pa.String, nullable=True, coerce=True),
},
    strict=True,
    coerce=True,
)
