import pandera as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
    'Centro de beneficio': Column(pa.String, nullable=True, coerce=True),
    'Sociedad': Column(pa.String, nullable=True, coerce=True),
    'Nº documento': Column(pa.Float, nullable=True, coerce=True),
    'Ejercicio': Column(pa.Float, nullable=True, coerce=True),
    'Clase de documento': Column(pa.String, nullable=True, coerce=True),
    'Fecha de documento': Column(pa.DateTime, nullable=True, coerce=True),
    'Fe.contabilización': Column(pa.DateTime, nullable=True, coerce=True),
    'Código transacción': Column(pa.String, nullable=True, coerce=True),
    'Número de contrato': Column(pa.Float, nullable=True, coerce=True),
    'Contrato anterior': Column(pa.String, nullable=True, coerce=True),
    'Referencia': Column(pa.String, nullable=True, coerce=True),
    'Cliente': Column(pa.Float, nullable=True, coerce=True),
    'Nº ident.fis.1': Column(pa.String, nullable=True, coerce=True),
    'Nombre': Column(pa.String, nullable=True, coerce=True),
    'Cuenta de mayor': Column(pa.Float, nullable=True, coerce=True),
    'Denominación': Column(pa.String, nullable=True, coerce=True),
    'Importe ML': Column(pa.Float, nullable=True, coerce=True),
    'Moneda': Column(pa.String, nullable=True, coerce=True),
    'Clase de condición': Column(pa.Float, nullable=True, coerce=True),
    'Denom.clase condición': Column(pa.String, nullable=True, coerce=True),
    'Anulado con': Column(pa.Float, nullable=True, coerce=True),
    'Ej.': Column(pa.Float, nullable=True, coerce=True),
    'Clave de referencia': Column(pa.String, nullable=True, coerce=True),
    'Documento comercial': Column(pa.Float, nullable=True, coerce=True),
    'Documento de ventas': Column(pa.Float, nullable=True, coerce=True),
    'Posición': Column(pa.Float, nullable=True, coerce=True),
    'Clase de contrato': Column(pa.Float, nullable=True, coerce=True),
    'Clase de movimiento': Column(pa.String, nullable=True, coerce=True),
    'Material': Column(pa.Float, nullable=True, coerce=True),
    'Texto breve de material': Column(pa.String, nullable=True, coerce=True),
    'Centro': Column(pa.String, nullable=True, coerce=True),
    'Cantidad': Column(pa.Float, nullable=True, coerce=True),
    'Unidad medida base': Column(pa.String, nullable=True, coerce=True),
},
    strict=True,
    coerce=True,
)
