import pandera as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
    'Cód. Empresa': Column(pa.Float, nullable=True, coerce=True),
    'Empresa': Column(pa.String, nullable=True, coerce=True),
    'Documento - Tipo': Column(pa.String, nullable=True, coerce=True),
    'PN - Codigo': Column(pa.String, nullable=True, coerce=True),
    'PN - Nome': Column(pa.String, nullable=True, coerce=True),
    'Documento - Data - Lancamento': Column(pa.DateTime, nullable=True, coerce=True),
    'Nº SAP': Column(pa.Float, nullable=True, coerce=True),
    'Documento - Numero da nota': Column(pa.Float, nullable=True, coerce=True),
    'Documento - Total': Column(pa.Float, nullable=True, coerce=True),
    'Documento - Status': Column(pa.String, nullable=True, coerce=True),
    'Documento - Data - Vencimento': Column(pa.DateTime, nullable=True, coerce=True),
    'Documento - Parcelas': Column(pa.String, nullable=True, coerce=True),
    'Parcela - Numero': Column(pa.Float, nullable=True, coerce=True),
    'Parcela - Status': Column(pa.String, nullable=True, coerce=True),
    'Parcela - Data - Vencimento': Column(pa.DateTime, nullable=True, coerce=True),
    'Parcela - Total': Column(pa.Float, nullable=True, coerce=True),
    'Parcela - Valor pago': Column(pa.Float, nullable=True, coerce=True),
    'Pagamento - Data de pagamento': Column(pa.DateTime, nullable=True, coerce=True),
    'Pagamento - Valor pago': Column(pa.Float, nullable=True, coerce=True),
    'Pagamento - Valor pago - Boleto': Column(pa.Float, nullable=True, coerce=True),
    'Pagamento - Valor pago - Cartao de credito': Column(pa.Float, nullable=True, coerce=True),
    'Pagamento - Valor pago - Cheque': Column(pa.Float, nullable=True, coerce=True),
    'Pagamento - Valor pago - Dinheiro': Column(pa.Float, nullable=True, coerce=True),
    'Pagamento - Valor pago - Transferencia bancaria': Column(pa.Float, nullable=True, coerce=True),
},
    strict=True,
    coerce=True,
)
