import pandera as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
    'Icono part.abiertas/comp.': Column(pa.Float, nullable=True, coerce=True),
    'Acreedor': Column(pa.String, nullable=True, coerce=True),
    'Nombre de Acreedor': Column(pa.String, nullable=True, coerce=True),
    'Cuenta': Column(pa.Float, nullable=True, coerce=True),
    'Sociedad': Column(pa.String, nullable=True, coerce=True),
    'Asignación': Column(pa.String, nullable=True, coerce=True),
    'Nº documento': Column(pa.Float, nullable=True, coerce=True),
    'División': Column(pa.Float, nullable=True, coerce=True),
    'Clase de documento': Column(pa.String, nullable=True, coerce=True),
    'Fecha de documento': Column(pa.DateTime, nullable=True, coerce=True),
    'Fe.contabilización': Column(pa.DateTime, nullable=True, coerce=True),
    'Fecha de pago': Column(pa.DateTime, nullable=True, coerce=True),
    'Clave contabiliz.': Column(pa.Float, nullable=True, coerce=True),
    'Impte.mon.local': Column(pa.Float, nullable=True, coerce=True),
    'Importe en moneda doc.': Column(pa.Float, nullable=True, coerce=True),
    'Moneda del documento': Column(pa.String, nullable=True, coerce=True),
    'Indicador impuestos': Column(pa.String, nullable=True, coerce=True),
    'Doc.compensación': Column(pa.Float, nullable=True, coerce=True),
    'Centro de beneficio': Column(pa.String, nullable=True, coerce=True),
    'Segmento': Column(pa.String, nullable=True, coerce=True),
    'Texto': Column(pa.String, nullable=True, coerce=True),
    'Clase cta.contrapar.': Column(pa.Float, nullable=True, coerce=True),
    'Cta.contrapartida': Column(pa.Float, nullable=True, coerce=True),
},
    strict=True,
    coerce=True,
)
