import pandera as pa
from pandera import Column, DataFrameSchema

schema = DataFrameSchema({
    'Id': Column(pa.Float, nullable=True, coerce=True),
    'Cuenta Aerodom': Column(pa.Float, nullable=True, coerce=True),
    'Cuenta Cockpit': Column(pa.String, nullable=True, coerce=True),
    'Cuenta Vision': Column(pa.String, nullable=True, coerce=True),
    'Nombre cuenta': Column(pa.String, nullable=True, coerce=True),
    'Nombre cuenta Cockpit': Column(pa.String, nullable=True, coerce=True),
    'Mapping dashboard': Column(pa.String, nullable=True, coerce=True),
    'Año': Column(pa.Float, nullable=True, coerce=True),
    'Presupuesto Id': Column(pa.String, nullable=True, coerce=True),
    'P&L': Column(pa.String, nullable=True, coerce=True),
    'Level1': Column(pa.String, nullable=True, coerce=True),
    'Level2': Column(pa.String, nullable=True, coerce=True),
    'Tipo Cuenta': Column(pa.Float, nullable=True, coerce=True),
    'Dirección': Column(pa.String, nullable=True, coerce=True),
    'Area': Column(pa.String, nullable=True, coerce=True),
    'Aeropuerto': Column(pa.String, nullable=True, coerce=True),
    'Ene': Column(pa.Float, nullable=True, coerce=True),
    'Feb': Column(pa.Float, nullable=True, coerce=True),
    'Mar': Column(pa.Float, nullable=True, coerce=True),
    'Abr': Column(pa.Float, nullable=True, coerce=True),
    'May': Column(pa.Float, nullable=True, coerce=True),
    'Jun': Column(pa.Float, nullable=True, coerce=True),
    'Jul': Column(pa.Float, nullable=True, coerce=True),
    'Ago': Column(pa.Float, nullable=True, coerce=True),
    'Sep': Column(pa.Float, nullable=True, coerce=True),
    'Oct': Column(pa.Float, nullable=True, coerce=True),
    'Nov': Column(pa.Float, nullable=True, coerce=True),
    'Dic': Column(pa.Float, nullable=True, coerce=True),
    'Total FY': Column(pa.Float, nullable=True, coerce=True),
},
    strict=True,
    coerce=True,
)
