from enum import Enum


class FinanceRefFileTypes(Enum):
    REFCUSTOMERS = "REFCUSTOMERS"
    REFSUPPLIERS = "REFSUPPLIERS"
    MAPPINGCLIENTSIATA = "MAPPINGCLIENTSIATA"
    MAPPINGCOSTCENTER = "MAPPINGCOSTCENTER"
    MAPPINGAIRPORTS = "MAPPINGAIRPORTS"
    MAPPINGACTIVITIES = "MAPPINGACTIVITIES"
    MAPPINGCOMPTESBUDGET = "MAPPINGCOMPTESBUDGET"
    MAPPINGENTITIES = "MAPPINGENTITIES"
    MAPPINGCAPEXCATEGORY = "MAPPINGCAPEXCATEGORY"
    MAPPINGCAPEX = "MAPPINGCAPEX"
